version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  nginx:
    image: nginx
    restart: always
    volumes:
    #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/templates/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    - "80:80"
    depends_on:
      - blog
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80

  blog:
    build: ./blog
    restart: always
    volumes:
      - ./blog:/blog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 3002:3002    
    environment:
      ELASTIC_URL: http://elasticsearch:9200
      MONGO_HOST: mongo:27017
      MONGO_USER: root
      MONGO_PASSWORD: example

  elasticsearch:
    image: elasticsearch:8.10.2
    ports:
      - '127.0.0.1:9200:9200'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      
  telegraf:
    image: telegraf:1.28.3-alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mongo
      - elasticsearch
    links:
      - influxdb
      - mongo
      - elasticsearch
    ports:
    - '127.0.0.1:8125:8125/udp'

  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: {}
  influxdb_data: {}
  mongodb_data: {}
